# Build image.
image: Visual Studio 2022
#cache: C:\projects\systeminformer

# Version format.
version: "#{build}"

# Only build the master branch.
branches:
  only:
    - master

# Do not increment build number after pull requests.
pull_requests:
  do_not_increment_build_number: true

# Do not start a new build when a new Git tag is created.
skip_tags: true

# Set the clone directory on the buildbot.
clone_folder: C:\projects\systeminformer

# Immediately finish build if something fails.
matrix:
  fast_finish: true

# Disable running any test assemblies.
test: off

# Run custom build script.
build_script:
- cmd: tools\CustomBuildTool\bin\Release\CustomBuildTool.exe -appveyor
