# Version format.
version: "Build #{build}"

# Only build the master branch.
branches:
  only:
    - master

# Do not increment build number after pull requests.
pull_requests:
  do_not_increment_build_number: true

# Do not start a new build when a new Git tag is created.
skip_tags: true
  
# Set the clone directory on the buildbot.
clone_folder: C:\projects\processhacker2

# Set clone depth.
clone_depth: 1

# Do not build on commits, only nightly builds.
# Force the nightly build by including the string "force-build" in the commit message.
skip_commits:
  author: /force-build/
  
# Immediately finish build if something fails.
matrix:
  fast_finish: true

# Install inno setup.
install:
  - choco install -y InnoSetup
  
# Disable running any test assemblies.
test: off

# Run custom build script.
build_script:
- ps: .\build\internal\nightly.ps1

# FTP deployment settings.
deploy:
- provider: FTP
  host: wj32.org
  protocol: sftp
  username: processhacker
  password:
    secure: lWdlTtxnMMQRjUQ8pndOBPBiJPn8b8ssP1qtSPzIj58=
  folder: /www/rel

# Deploy these files to our ftp.
artifacts:
- path: .\processhacker-nightly-setup.exe
  name: processhacker-nightly-setup.exe
- path: .\processhacker-nightly-bin.zip
  name: processhacker-nightly-bin.zip
- path: .\processhacker-nightly-sdk.zip
  name: processhacker-nightly-sdk.zip
- path: .\processhacker-nightly-src.zip
  name: processhacker-nightly-src.zip
- path: .\processhacker-nightly-checksums.txt
  name: processhacker-nightly-checksums.txt

# Setup build notifications.
notifications:
- provider: Email
  to:
  - dmex04@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false