name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@adf501690e8c591553001c8b0027580ce0ccb398
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_ASSISTANT_TOKEN }}
        with:
          path-to-signatures: 'systeminformer/cla-signatures.json'
          path-to-document: 'https://github.com/winsiderss/systeminformer/blob/master/CLA.md'
          branch: 'main'
          remote-organization-name: 'winsiderss'
          remote-repository-name: 'winsiderss-cla'
          lock-pullrequest-aftermerge: true
